name: Multi Container Setup
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t laitapee/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true laitapee/react-test npm test
      - run: docker build -t laitapee/multi-client-01-20 ./client
      - run: docker build -t laitapee/multi-server-01-20 ./server
      - run: docker build -t laitapee/multi-worker-01-20 ./worker
      - run: docker build -t laitapee/multi-nginx-01-20 ./nginx

      - run: docker push laitapee/multi-client-01-20
      - run: docker push laitapee/multi-nginx-01-20
      - run: docker push laitapee/multi-server-01-20
      - run: docker push laitapee/multi-worker-01-20

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-373029353725
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip